logging:
  level:
#    com.zaxxer.hikari: debug
#    org.springframework.jdbc.core.JdbcTemplate: debug
    io.jaegertracing.internal.reporters.LoggingReporter: WARN
    org.springframework.web.servlet.DispatcherServlet: debug
    de.neebs: debug
#    org.springframework.jdbc.core: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
server:
  port: 8079
  servlet:
    context-path: /
spring:
  main:
    banner-mode: "off"
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin123
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    app-version: '@app.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
