package de.neebs.spacepeoples.integration.database;

public enum BuildingType {
    BUILDING_YARD, ELECTROLYSIS_PLANT, FOUNTAIN, IRON_MINE, CARBON_MINE, SILICON_MINE, PLANET_DEFENSE_UNIT, SPACESHIP_FACTORY, SPACESHIP_HARBOUR, SPACESHIP_RESEARCH_FACILITY
}
