package de.neebs.spacepeoples.integration.database;

public enum BuildingTypeEnum {
    BUILDING_YARD,
    SPACEPORT,
    RESIDENTIAL_BUILDING,
    SOLAR_PARK,
    RECYCLING_FACILITY,
    IRON_MINE,
    SILICON_MINE,
    CARBON_MINE,
    FOUNTAIN,
    ELECTROLYSIS_PLANT,
    WAREHOUSE,
    SPACESHIP_FACTORY,
    WEAPON_FACTORY,
    SPACESHIP_RESEARCH_FACILITY
}
