package de.neebs.spacepeoples.integration.database;

public enum BuildingTypeEnum {
    BUILDING_YARD, ELECTROLYSIS_PLANT, FOUNTAIN, IRON_MINE, CARBON_MINE, SILICON_MINE, PLANET_DEFENSE_UNIT, SPACESHIP_FACTORY, SPACEPORT, SPACESHIP_RESEARCH_FACILITY
}
