INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('BASIC_UNIT', 'STABILITY', 12150, 5400, 1.11, 0.91, 0, 1, 200, 1.09, -0.545);

INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('CARGO_MODULE', 'CARGO', 8100, 4500, 1.11, 0.91, 0, 1, 600, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('FUEL_TANK', 'FUEL', 8100, 4500, 1.11, 0.91, 0, 1, 600, 1.09, -0.545);

INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('ARMOUR', 'DEFENSE', 16200, 7200, 1.11, 0.91, 0, 1, 15, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('SHIELD', 'DEFENSE', 16200, 7200, 1.11, 0.91, 0, 1, 15, 1.09, -0.545);

INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('COMBUSTION_DRIVE', 'ACCELERATION', 6075, 2700, 1.11, 0.91, 0, 1, 20000, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('FUSION_DRIVE', 'ACCELERATION', 24300, 10800, 1.11, 0.91, 0, 1, 10000, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('TIME_WARP_DRIVE', 'WARP', 60750, 27000, 1.11, 0.91, 0, 1, 100000000, 0.91, 0);

INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('ROCKET', 'ATTACK', 6075, 2700, 1.11, 0.91, 0, 1, 30, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('LASER', 'ATTACK', 20250, 9000, 1.11, 0.91, 0, 1, 45, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('PLASMA', 'ATTACK', 48600, 21600, 1.11, 0.91, 0, 1, 60, 1.09, -0.545);

INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('SPY_UNIT', 'SPECIAL_UNIT', 4050, 2700, 1.11, 0.91, 15, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('CAMOUFLAGE_UNIT', 'SPECIAL_UNIT', 24300, 5400, 1.11, 0.91, 15, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('COLONISATION_UNIT', 'SPECIAL_UNIT', 54000, 72000, 1.11, 0.91, 15, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('INVASION_UNIT', 'SPECIAL_UNIT', 64800, 86400, 1.11, 0.91, 15, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('RECYCLING_UNIT', 'SPECIAL_UNIT', 12150, 5400, 1.11, 0.91, 10, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('BOUNTY_UNIT', 'SPECIAL_UNIT', 20250, 8100, 1.11, 0.91, 10, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('SABOTAGE_UNIT', 'SPECIAL_UNIT', 40500, 10800, 1.11, 0.91, 10, 0, 0, 1.09, -0.545);
INSERT INTO research_type (research_type, characteristic, research_in_seconds, building_in_seconds, duration_level_base, facility_base, space_fix, space_per_level, benefit_basic_value, benefit_base, benefit_exponent_modifier) VALUES ('MINERAL_PROCESSOR', 'SPECIAL_UNIT', 40500, 5400, 1.11, 0.91, 0, 1, 0, 1.09, -0.545);
