INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('BUILDING_YARD', 'Building Yard', 21600, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('SPACEPORT', 'Building Yard', 36000, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('RESIDENTIAL_BUILDING', 'Residential Building', 3600, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('SOLAR_PARK', 'Solar Park', 7200, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('IRON_MINE', 'Iron Mine', 10800, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('SILICON_MINE', 'Silicon Mine', 10800, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('CARBON_MINE', 'Carbon Mine', 10800, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('FOUNTAIN', 'Fountain', 10800, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('ELECTROLYSIS_PLANT', 'Electrolysis Plant', 18000, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('WAREHOUSE', 'Warehouse', 3600, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('RECYCLING_FACILITY', 'Recycling Facility', 19600, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('SPACESHIP_FACTORY', 'Spaceship Factory', 43200, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('WEAPON_FACTORY', 'Weapon Factory', 43200, 1.11, 0.91);
INSERT INTO building_type(building_type, name, duration_in_seconds, level_base, building_yard_base) VALUES ('SPACESHIP_RESEARCH_FACILITY', 'Spaceship Research Facility', 43200, 1.11, 0.91);
